version: '3.8'

services:
  postgres:
    container_name: "video-streaming-postgres"
    image: postgres:17.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: video-streaming

  minio:
    container_name: "video-streaming-minio"
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin

volumes:
  minio-data:
    driver: local