CREATE TABLE file_metadata
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255) NOT NULL,
    uuid         UUID UNIQUE NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    content_size BIGINT NOT NULL,
    uploaded_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_file_matadata PRIMARY KEY (id)
);